package pixelCombat.enums;

// bilal
/**
 * KeyCommand
 * 
 * @author BillyG
 * @version 0.1
 */
public enum KeyCommand {

	P1LEFT, P1RIGHT, P1BASICATTACK1,P1BASICATTACK21,P1BASICATTACK22,P1BASICATTACK23, P1JUMP,P1SPECIALATTACK3,P2SPECIALATTACK3, P1COMBOATTACK,P1DASH, P1SPECIALATTACK2, P2LEFT, P2RIGHT, P2JUMP, P2COMBOATTACK, P2SPECIALATTACK2, P2BASICATTACK1, ENTER, SOUNDOFF, SOUNDON, P1BASICATTACK2, P1SPECIALATTACK1, P2DASH, P2BASICATTACK2, P2SPECIALATTACK1,P1DEFEND, P2DEFEND, P1SPECIALATTACK4, P2SPECIALATTACK4,P1SPECIALATTACK5, P2SPECIALATTACK5,P1SPECIALATTACK6, P2SPECIALATTACK6,P2BASICATTACK21,P2BASICATTACK22,P2BASICATTACK23, P1AIRSPECIALATTACK1, P2AIRSPECIALATTACK1, BACK_SLASH, P1DOWN, P2DOWN, 

}
