package pixelCombat.enums;

public enum TimeState {
	DOWN, 
	DISABLETIME,
	BLINKTIME, 
	JUMPDELAY, 
	DASHANDRETREATDELAY,
	DEFENDRELEASETIME,
	BASICATTACK1_BUFFERTIME,
	BASICATTACK2_BUFFERTIME,
	SPECIALATTACK1_BUFFERTIME,
	SPECIALATTACK2_BUFFERTIME,
	SPECIALATTACK3_BUFFERTIME,
	SPECIALATTACK4_BUFFERTIME
}
